### PR TITLE
Update start-template for systemd

### PR DESCRIPTION
**Pull request by kononencheg**
sighup for reload

### CODE REVIEW

**Comment by kardapoltsev** [comment]
Nice addition! It would be great if you add the same feature to other system loaders (`SystemV` and `Upstart`) (:

**Comment by muuki88** [comment]
@kardapoltsev would this be simple to do? For upstart maybe, but for SystemV I think this is though :p 
For me this looks good to merge. Any further improvements would be awesome, but not required IMO.

**Comment by kardapoltsev** [comment]
> And I'm not 100% sure what this addition does xD

It only sends `SIGHUP (1)` signal to application.
Additions would be great but definitely isn't required. For `SystemV` it could look like
```bash
 reload)
    status_of_proc -p "$PIDFILE" "$RUN_CMD" ${{app_name}} > /dev/null || /bin/kill -HUP "${PIDFILE}"
    ;;
```
I didn't test it.

**Comment by kardapoltsev** [comment]
@kononencheg do you plan to add smth? If not it's fine to merge it as is IMHO.

**Comment by kononencheg** [comment]
@kardapoltsev no, that's all.

**Comment by kardapoltsev** [comment]
Thanks, this is a nice feature for some apps!

**Pull request merged**
