### PR TITLE
Included feature publishM2

### PR DESCRIPTION
**Pull request by giorgioinf**
# Feature request - publishM2

It's a small change including a publishM2 action. Currently the sbt-native-packages only supports`publish` and `publishLocal` actions. 

## Tested on

- **O.S.:** MacOSX, Darwin <host> 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
- **bash:** GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
- **sbt:** 1.1.1
- **scala:** Scala code runner version 2.12.5 -- Copyright 2002-2018, LAMP/EPFL and Lightbend, Inc
- **java jdk:** java version "1.8.0_162",Java(TM) SE Runtime Environment (build 1.8.0_162-b12), Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @giorgioinf,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by giorgioinf** [comment]
Issue: #1114

**Comment by giorgioinf** [comment]
How can we deal with this error at .m2 diretory, when it is building a package at second time?

```[info] [error] java.io.IOException: Destination file file:/home/travis/.m2/repository/simple-test/simple-test/0.1.0/simple-test-0.1.0.zip exists and overwrite == false```

**Comment by muuki88** [comment]
The `validateUniversal` step fails on travis. 
https://travis-ci.org/sbt/sbt-native-packager/jobs/359292008#L1246

```
[info] [error] java.io.IOException: Destination file file:/home/travis/.m2/repository/simple-test/simple-test/0.1.0/simple-test-0.1.0.zip exists and overwrite == false
[info] [error] 	at sbt.internal.librarymanagement.ConvertResolver$LocalIfFileRepo.put(ConvertResolver.scala:370)
```

It looks like that there is already a released file. We could either set the `overwrite` to false or try a `SNAPSHOT` version.

**Comment by muuki88** [comment]
Sorry for my last (now deleted) comment. I haven't seen your last comment, which already addressed this issue.

I would go `isSnapshot in ThisBuild := true` and put a small comment in there why we need it.

**Pull request merged**
