### PR TITLE
Treat symlinks as normal files in spec file

### PR DESCRIPTION
**Pull request by muuki88**
Updated PR from #901

### CODE REVIEW

**Comment by erickpintor** [comment]
Hi @muuki88. I'm interested in this change. What's the current state of it?

**Comment by muuki88** [comment]
Hi @erickpintor
I hadn't had any time to test this on my own. @dpennell started the implementation and I think he ted this back then. However things may need to be adapted since this is a very old PR.

Would you have the time to finish this PR?

**Comment by muuki88** [comment]
I'm currently on vacation. It may take some time for me to answer.

**Comment by erickpintor** [comment]
@muuki88 I've created a new PR for this: https://github.com/sbt/sbt-native-packager/pull/1039

**Comment by muuki88** [comment]
You are awesome 🤩

**Pull request closed without merging**
