### PR TITLE
fix packageZipTarball defaults for UniversalDocs and UniversalSource

### LINKED ISSUE #1019: packageZipTarball defaults not provided for UniversalDocs and UniversalSource, as it is with Universal
## Expected behaviour

When I run this:

```
sbt universal-docs:package-zip-tarball
```

It should run tar with the options `-pcvf`, as occurs with `sbt universal:package-zip-tarball`

## Actual behaviour

Tar is invoked without any flags, and fails:

```
Running with tar /var/folders/hb/5j3hrbpn4v90q03nf_qfqncm0000gr/T/sbt_c510d681/marathon-1.5.0-SNAPSHOT-734-g6d018f7.tar marathon-1.5.0-SNAPSHOT-734-g6d018f7
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
```

## Information

- v1.2.2

### PR DESCRIPTION
**Pull request by timcharper**
The implementation clearly fell short of the intention.

fixes #1019

### CODE REVIEW

**Comment by timcharper** [comment]
Failures do not appear to be related to my patch

**Comment by muuki88** [comment]
I updated the branch, hopefully fixing the travis-ci errors.

**Comment by timcharper** [comment]
@muuki88 can you narrow the search space for me on where to put such a test? :) Give me a few clues? I see the sbt scripting automation but none of the tests seem to run on my laptop. (I have a debian machine I can use... just not available at the moment)

**Comment by muuki88** [comment]
Ah! My bad @timcharper :grinning: 

[The univeral/test-zips](https://github.com/sbt/sbt-native-packager/blob/master/src/sbt-test/universal/test-zips/test) test should be sufficient if you just add the `universalDoc:packageBin`, etc. tasks.

**Comment by muuki88** [comment]
hi @timcharper :)
Do you need any help?

**Comment by muuki88** [comment]
I'll be on vacation un 20.10. Thanks for your understanding if this can't be merged until then

**Comment by muuki88** [comment]
Thanks for your work here @timcharper 
I opened a new pull request to get this fix into master :)

**Pull request closed without merging**
