### PR TITLE
Add link to working example of BuildEnvPlugin

### PR DESCRIPTION
**Pull request by ryanberckmans**
It took me awhile to figure out how to run the scalac optimizer for only a production build. I used the BuildEnvPlugin described here and thought readers might benefit from the docs linking to a working example.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @ryanberckmans,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ryanberckmans** [comment]
I signed the Lightbend Contributors License Agreement.

**Comment by nigredo-tori** [comment]
Maybe we should simplify the code itself, so that everything happens in `build.sbt`? Like
```scala
ThisBuild / buildEnv := ...
ThisBuild / onLoadMessage := ...

lazy val appPackage = project
  // we put the results  in a build folder
  .in(file("app-package"))
  .enablePlugins(JavaAppPackaging)
  .settings(
    mappings in Universal += {
      val confFile = buildEnv.value match {
	case BuildEnv.Developement => "dev.conf"
	case BuildEnv.Test => "test.conf"
	case BuildEnv.Stage => "stage.conf"
	case BuildEnv.Production => "prod.conf"
      }
      ((resourceDirectory in Compile).value / confFile) -> "conf/application.conf"
    }
  )
  .dependsOn(app)
```
`AutoPlugin` feels too heavy for a simple example.

**Comment by ryanberckmans** [comment]
That sounds good to me. I wasn't sure how to get it working with only code in build.sbt.

**Comment by muuki88** [comment]
Thanks a lot for sharing your work 😊

I'm totally fine with merging this. There is an existing collection of examples here: https://github.com/muuki88/sbt-native-packager-examples

You could also add it there

**Comment by ryanberckmans** [comment]
@muuki88 good idea!  https://github.com/muuki88/sbt-native-packager-examples/pull/16

Can we also merge it here? It's nice to have a reference to a working example at the site of the pertinent docs.

**Comment by muuki88** [comment]
Done :)

**Pull request merged**
