### PR TITLE
add maven metadata required by sonatype

### PR DESCRIPTION
**Pull request by jozic**
a step toward fixing #906 

@muuki88 please review

### CODE REVIEW

**Comment by muuki88** [comment]
Thanks for your work. I'll check with the sbt devs how we can implemented the maven sync.

**Comment by muuki88** [comment]
I started [a discussion on sbt-dev](https://gitter.im/sbt/sbt-dev?at=5839a56ab4d7ca3b7a175edb). I'll need to test this with bintray in a pet project to see if the plugin resolving still works out of the box.

**Comment by muuki88** [comment]
@jozic I'm afraid we won't be able to realize publishing to maven. I was curious if this is possible, but it seems to be a lot trickier then I first anticipated. It seems sbt plugins heavily rely on the ivy layout. The maven layout  doesn't support the sbt version number.

I'm afraid the workarounds will raise the barriers to contribute to this project. Sorry for not being able to do this. You'll have to go with a local build or artifactory.

**Comment by jozic** [comment]
@muuki88 I guess it's your call,
but AFAIU @fommil got sbt-ensime published to sonatype with sbt version
do you say the way he did it can build a barrier for other contributors? could you please explain why?

**Comment by muuki88** [comment]
> do you say the way he did it can build a barrier for other contributors

Nope. I'm not into the details on sbt-ensime. Sam revived ensime and I guess started from the beginning to publish to sonatype. Also ecosystem is a lot different than native-packagers.

 > could you please explain why?

Onboarding a new contributor how can release requires two steps
- adding him/her as a commiter
- grant access to publish to [sbt-plugin-releases](http://bintray.com/sbt/sbt-plugin-releases) ( which can be done by all the sbt maintainers AFAIK )

Using Sonatype [requires authorization by Sonatype](http://central.sonatype.org/pages/ossrh-guide.html) to publish under a certain domain. In this case `com.typesafe.sbt.packager`. This is one step more a new maintainer has to take. The governance is also not in the hands of Lightbend ( typesafe ) but Sonatype. 

Further more this complicates the build process. All sbt plugins I know are published on bintray. This is extra complexity, which makes maintaining more time consuming.

However most importantly this is a time issue. I maintain this project in my spare time. While I'm happy for all the awesome contributions, I spent my time mostly on cleaning up the code base, reducing technical depth and writing docs to make it easier to contribute.

Publishing to maven central would cost me at least 2-3 days with
- getting credentials
- update the build process
- figure out this even works
- test the impact on users
- still release to bintray
- document everything

If your employer sets up this ( IMHO not really useful restrictions ), he/she should pay you to workaround them ( while I'm not getting paid for fixing home made issue). I'm really interested in seeing a fork that accomplishes this. So go ahead :smile: 

So please understand that I see no point in fixing this issue for native-packager as adds no value to the project. And yes, there are companies like yours that restrict to maven central, but if they have such rules they must pay their employees to work around them. The main reason I started looking into that was because I was curious if things would work. And the answers is "well, maybe. But not quite sure how and with how many hacks".

**Pull request closed without merging**
