### PR TITLE
Experimental support for formats generated by the JDK 8 `javapackager` tool.

### PR DESCRIPTION
**Pull request by metasim**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @metasim,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://typesafe.com/contribute/cla](http://typesafe.com/contribute/cla)

**Comment by muuki88** [comment]
Smooth! I had time to test it on my Ubuntu system and it worked perfectly for deb files.
Complaining about `rpm`, but that's a _javapackager_ issue I guess.

I'll test this on windows as well. It would be awesome if you add the sphinx docs as well.
If you need any help on this, just ping me.

**Comment by metasim** [comment]
I signed the CLA and put some basic docs in the README.md. I'll try to get to the sphinx docs this weekend, but don't hold your breath. I need to add JVM arguments support for my day job.

**Comment by muuki88** [comment]
So, I took a closer look on windows as well. You are hitting a 'bug', which will be
solved in #487 (`chmod` cannot be used on windows).

Also the `locateJDKPackagerTool()` did work on windows, I had to set the
setting with

```scala
jdkPackagerTool := Some(file("C:\\Program Files\\Java\\jdk1.8.0_31\\bin\\javapackager.exe"))
```

the error messages are helpful, but could use some examples. 

Having said that. I will try to pull off a release tomorrow and I would
like to get this out in the wild for very-early adopters. If you can
add

- documentation
- examples in errors messages

this would be nice, but can be added in another pull request as well.
Some scripted tests would be nice as well, but we create some on the
way.

**Comment by metasim** [comment]
Can you point me to an example of "examples in error messages"?

I'll look into the windows packager lookup issue (now where'd I put vmware...). Should I create a github issue for it?

**Pull request merged**
