### PR TITLE
Make `sbt docker:stage` work on Windows

### LINKED ISSUE #823: `sbt docker:stage` fails on Windows 10
This is related to #573 

Steps to reproduce on Windows 10 machine (I tried using both bash.exe and cmd.exe):

- Check out `sbt-native-packager` master branch
- Go to test-project-docker folder
- Run `sbt docker:stage`

You get stack trace

```
java.lang.ArrayIndexOutOfBoundsException: 1
        at com.typesafe.sbt.packager.docker.DockerPlugin$.com$typesafe$sbt$packager$docker$DockerPlugin$$makeAdd(DockerPlugin.scala:162)
        at com.typesafe.sbt.packager.docker.DockerPlugin$$anonfun$projectSettings$8.apply(DockerPlugin.scala:89)
        at com.typesafe.sbt.packager.docker.DockerPlugin$$anonfun$projectSettings$8.apply(DockerPlugin.scala:80)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

What seems to have happened is that https://github.com/sbt/sbt-native-packager/commit/f52167977e74187a284f5b8392e3bdb64c05b4b6 (#573, #588) has been reverted by https://github.com/sbt/sbt-native-packager/commit/101311e4f967cc0117e05358960097b5915b2b38 (#760, #765)  in 1.1.1

### PR DESCRIPTION
**Pull request by oporkka**
Closes #823

---
This change is [Reviewable](https://reviewable.io/reviews/sbt/sbt-native-packager/824)

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @oporkka,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by muuki88** [comment]
Were you able to run the `sbt scripted docker/*` tests?

Thanks for the extensive documentation on this issue :)

**Comment by oporkka** [comment]
My pleasure!

`sbt scripted docker/*` fails both in this branch and current master branch. There's stacktrace like
```
[info] java.io.IOException: Cannot run program "C:\Users\Oskari\AppData\Local\Temp\sbt_a8dde3df\simple-app\target\universal\stage\bin\simple-app" (in directory "C:\Users\Oskari\AppData\Local\Temp\sbt_a8dde3df\simple-app\target\universal\stage"): CreateProcess error=193, %1 is not a valid Win32 application
[info]  at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
[info]  at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
[info]  at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:160)
[info]  at sbt.AbstractProcessBuilder.getString(ProcessImpl.scala:133)
[info]  at sbt.AbstractProcessBuilder.$bang$bang(ProcessImpl.scala:136)
[info]  at $e918e65b4ee909c26cd3$$anonfun$$sbtdef$1.apply(C:\Users\Oskari\AppData\Local\Temp\sbt_a8dde3df\simple-app\build.sbt:10)
[info]  at $e918e65b4ee909c26cd3$$anonfun$$sbtdef$1.apply(C:\Users\Oskari\AppData\Local\Temp\sbt_a8dde3df\simple-app\build.sbt:7)
[info]  at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[info]  at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[info]  at sbt.std.Transform$$anon$4.work(System.scala:63)
[info]  at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]  at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]  at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[info]  at sbt.Execute.work(Execute.scala:237)
[info]  at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]  at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]  at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[info]  at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[info]  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]  at java.lang.Thread.run(Thread.java:745)
[info] Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
[info]  at java.lang.ProcessImpl.create(Native Method)
[info]  at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
[info]  at java.lang.ProcessImpl.start(ProcessImpl.java:137)
[info]  at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
[info]  at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
[info]  at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:160)
[info]  at sbt.AbstractProcessBuilder.getString(ProcessImpl.scala:133)
[info]  at sbt.AbstractProcessBuilder.$bang$bang(ProcessImpl.scala:136)
[info]  at $e918e65b4ee909c26cd3$$anonfun$$sbtdef$1.apply(C:\Users\Oskari\AppData\Local\Temp\sbt_a8dde3df\simple-app\build.sbt:10)
[info]  at $e918e65b4ee909c26cd3$$anonfun$$sbtdef$1.apply(C:\Users\Oskari\AppData\Local\Temp\sbt_a8dde3df\simple-app\build.sbt:7)
[info]  at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[info]  at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[info]  at sbt.std.Transform$$anon$4.work(System.scala:63)
[info]  at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]  at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]  at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[info]  at sbt.Execute.work(Execute.scala:237)
[info]  at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]  at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]  at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[info]  at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[info]  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]  at java.lang.Thread.run(Thread.java:745)
```

**Comment by muuki88** [comment]
The stacktrace looks strange. We need some ci for windows+docker :/ Hopefully appveyor will over something in the future.

**Comment by muuki88** [comment]
thanks for fixing this :)

**Comment by oporkka** [comment]
@muuki88  added #842 for backport

**Pull request merged**
