### PR TITLE
Specify working directory for graalvm-native-image

### LINKED ISSUE #1495: Invalid working directory on graalvm-native-image
## Expected behaviour

`sbt graalvm-native-image:packageBin` generates artifacts in `target/graalvm-native-image`.

GraalVM `native-image` output should be
```
Produced artifacts:
 /opt/graalvm/example (executable)
 /opt/graalvm/example.build_artifacts.txt
```

## Actual behaviour

`sbt graalvm-native-image:packageBin` generates no artifacts in `target/graalvm-native-image`.

GraalVM `native-image` is
```
Produced artifacts:
 /example (executable)
 /example.build_artifacts.txt
```

## GraalVM docker image

`GraalVMNativeImage / containerBuildImage := Some(s"ghcr.io/graalvm/native-image:ol8-java17-22.0.0.2")`

## Information

- sbt-native-packager version is `1.9.7`
- sbt version is `1.6.2`
- build system is Gentoo (Linux version is `5.15.11`)

## Possible solutions

- Add `"--workdir", "/opt/graalvm"` to [`docker run` arguments](https://github.com/sbt/sbt-native-packager/blob/v1.9.7/src/main/scala/com/typesafe/sbt/packager/graalvmnativeimage/GraalVMNativeImagePlugin.scala#L143)
- Add `graalVMNativeImageDockerOptions` for user to be able to specify such options.

### PR DESCRIPTION
**Pull request by senia-psm**
Fix #1495

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @senia-psm,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by senia-psm** [comment]
Sorry, I have no idea how to cover this with tests.

**Review by muuki88 — APPROVED** [review]
If the current tests run, this should be finde :hear_no_evil:

**Comment by muuki88** [comment]
version `1.9.8` is on its way

**Pull request merged**
