### PR TITLE
Support for 'Provides' and 'Conflicts' sections for debian packaging

### LINKED ISSUE #801: Rpm and Deb packaging is missing 'provides' and 'conflicts' tags/sections
Those sections are essential for package management and package relationship descriptions.

### PR DESCRIPTION
**Pull request by 412b**
includes changes to code, tests and docs

Fixes #801

### CODE REVIEW

**Comment by 412b** [comment]
@muuki88 can you review this one?

**Comment by muuki88** [comment]
LGTM. awesome work

**Comment by muuki88** [comment]
Sorry for the codacy errors. We still need to do a lot of cleanup.

**Comment by 412b** [comment]
@muuki88 no worries about codacy
is there any rough ETA for release with that commit?

**Comment by muuki88** [comment]
I plan to release a milestone this weekend after merging two other open pull requests.

**Pull request merged**
