### PR TITLE
Fixes #1542 - GraalVMNativeImagePlugin ignores resources in src/graal

### LINKED ISSUE #1542: GraalVMNativeImagePlugin ignores resources in src/graal
## Expected behaviour

I expect that files located in `src/graal`  will be included in the native-image classpath and packaged into the image as resources taking into account that I reference using `-H:IncludeResources` to my resource. 

## Actual behaviour

The files become available under `/opt/graalvm/stage/resources` in a docker container, but they are not included in the classpath and not included in the binary image. 

## Information

This is the configuration:

``` scala
.enablePlugins(GraalVMNativeImagePlugin)
.settings(
 ...
    GraalVMNativeImage / mainClass := Some("info.mshaper.EntryPoint"),
    GraalVMNativeImage / containerBuildImage := GraalVMNativeImagePlugin.generateContainerBuildImage( "aws_lnx2_graalvm") .value
graalVMNativeImageOptions := Seq(... , -H:IncludeResources=seed.conf , ...)
...
)
```
sbt-native-packager plugin version 1.9.16
GraalVM 22.3.1 Java 19 CE (Java Version 19.0.2+7-jvmci-22.3-b12)

I couldn't get how to log command that is being executed from sbt, so I used another bug in the plugin in order to print the error message that includes the CMD (The bug: the plugin ignores `graalVMNativeImageCommand`). The -cp in the command line doesn't include `/opt/graalvm/stage/resources` directory, so the resources are not included in the image.

### PR DESCRIPTION
**Pull request by heaven-born**
Fixes #1542

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @heaven-born,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by heaven-born** [comment]
I signed the CLA

**Review by muuki88 — COMMENTED** [review]
Thanks for your PR. I'm not too familiar with graalvm, but sounds legit that you want to include resources.

Did the `Universal / mappings` setting not workout for you?

**Comment by heaven-born** [comment]
Doesn't look like `Universal / mappings` has any effect on `GraalVMNativeImagePlugin`, but I tried just in case, and it didn't work out. 
But even if it did, it wouldn't be the way as it is documented in https://www.scala-sbt.org/sbt-native-packager/formats/graalvm-native-image.html  : 

>If you are building the image in a docker container, and you have any resources that need to be available to the native-image command, such as files passed to -H:ResourceConfigurationFiles or -H:ReflectionConfigurationFiles, you can place these in your projects src/graal directory. Any files in there will be made available to the native-image docker container under the path /opt/graalvm/stage/resources.

Currently, all resources placed in `src/graal` directory are not accessible for `-H:ResourceConfigurationFiles` and `-H:ReflectionConfigurationFiles`, because `/opt/graalvm/stage/resources` is not in  classpath.

**Comment by heaven-born** [comment]
I signed the CLA, should I restart the build somehow to make this check pass now?

**Review by muuki88 — APPROVED** [review]

**Comment by muuki88** [comment]
I'll release ASAP

**Comment by muuki88** [comment]
Version `1.9.17` is on it's way

**Comment by heaven-born** [comment]
looks like something went wrong with the build

**Pull request merged**
