### PR TITLE
handle -agentpath/-javaagent options

### PR DESCRIPTION
**Pull request by nicoulaj**
`-agentpath`/`-javaagent` options should go before classpath like `-agentlib`

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @nicoulaj,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Review by muuki88 — DISMISSED** [review]
Thanks a lot :smile:

**Comment by nicoulaj** [comment]
@muuki88 thanks, CLA should be good now

**Review by muuki88 — APPROVED** [review]

**Comment by muuki88** [comment]
I'll release next week ☺️

**Pull request merged**
