### PR TITLE
defaultLinuxLogsLocation not applied to start-rpm-template

### PR DESCRIPTION
**Pull request by louisq**
Where an application is installed using an RPM and the defaultLinuxLogsLocation is set the rpm would correctly create the logging folders for the application at the new location. Unfortunately the daemon would still try to log in the default location which was hard coded which resulted in the daemon failing. 

    [louisq@localhost APPNAME]$ sudo rpm -Uvh target/rpm/RPMS/noarch/APPNAME-45-0.noarch.rpm 
    [sudo] password for louisq: 
    Preparing...                ########################################### [100%]
    Creating system group: APPNAME
    Creating system user: APPNAME in APPNAME with APPNAME user-daemon and shell /bin/false
       1:APPNAME                   ########################################### [100%]
    Adding APPNAME to autostart using chkconfig
    Starting APPNAME: [  OK  ]
    bash: /var/log/APPNAME/daemon.log: No such file or directory

This change removes the hard coding from the logging in the start-rpm-template to instead use the value which originates from the LinuxPlugin. If the value is overridden the daemon will now log to the specified location.

An RPM built with those changes was run on a centos 6.7 machine and the universal/* and rpm/* tests were all run successfully

### CODE REVIEW

**Comment by muuki88** [comment]
LGTM.  Can you add a regression test for this? Here is a [small developer guide](https://github.com/sbt/sbt-native-packager/wiki/Developer-Guide) on how to run the tests. if you need any help, just ping here.

**Comment by louisq** [comment]
Thank you. Will do that tomorrow when I come back from an obligation that I have

**Comment by louisq** [comment]
Thank you for the link to the guide.
Added additional test that validates that the defaultLinuxLogLocation overrides the value in the init.d file generated with the rpm. Also added coverage for the defaultLinuxInstallLocation which can also be overridden in this file. Is there something else that you would like to see?

**Comment by muuki88** [comment]
Awesome. Can you squash the commits into one? Then this is ready to merge :)

**Comment by louisq** [comment]
Completed the rebase of the branch

**Pull request merged**
