### PR TITLE
Normalize  paths when mapping generic files to docker

### LINKED ISSUE #1329: Error due to path separator inconsistency on windows
## Expected behaviour

`sbt stage` executed on windows should generate a consistent dockerfile, in terms of paths description.

## Actual behaviour

Some paths in the output Dockerfile mix / and \\, resulting in an error when building the image.

## Information

- sbt-native-packager:  1.7.0
- sbt version: 1.3.8
- build system: Windows
- Package built: docker

## Reproduction

I'm using a custom start script, called "startDocker.sh" and put in <project home>/src/universal/bin

When adding a custom entrypoint in sbt
```
dockerEntrypoint := Seq("/opt/docker/bin/startDocker.sh")
```

the result on macos / linux contains  (as expected):
```
RUN ["chmod", "u+x,g+x", "/1/opt/docker/bin/startDocker.sh"]
```

but on windows, the same line is 
```
RUN ["chmod", "u+x,g+x", "/1/opt/docker/bin\startDocker.sh"]
```

I would not bother too much about this if the consequence wasn't docker to return the following error when running docker build (or docker:publish)
```
Step 12/25 : RUN ["chmod", "u+x,g+x", "/opt/docker/bin\startDocker.sh"]
 ---> Running in f6b9fec09930
/bin/sh: 1: [chmod,: not found
The command '/bin/sh -c ["chmod", "u+x,g+x", "/opt/docker/bin\startDocker.sh"]' returned a non-zero code: 127
```

### PR DESCRIPTION
**Pull request by cchafer**
Fixes #1329

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @cchafer,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by lightbend-cla-validator** [comment]
Hi @cchafer,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by muuki88** [comment]
Thanks a lot for tackling this issue. I'll be unavailable the next week to review this with the appropriate time.

Could you add a sbt-test that verifies this behaviour. Bonus points if there's one on Windows, Linux and MacOS 🤯♥️

**Comment by cchafer** [comment]
I would like to say yes, but to be honest, I think I won't be able to do it.
i'm working on MacOS, and : 
1. Sbt native packager doesn't compile on catalina with JDK 11 installed (I can create a new ticket for that)
2. Coding, on macOs, a pluging that needs to create a dockerfile on windows, to be used on linux, is.... quite slow and complicated :D I had to create docker images just for that, and test process is SO slow...
3. And the most important : I do not understand  your codebase enough...
4. I don't even think this is doable, since the docker part of native-packager just doesn't work at all on Docker for Windows....

Juste tu resume, I'd be happy to help, but without more help / guidance, I'm afraid I can't.

**Comment by cchafer** [comment]
Just one example to make my point, ***sbt-test/entrypoint/test*** :
`$ exec grep -q -F 'ENTRYPOINT ["/bin/sh", "-c", "env"]' target/docker/stage/Dockerfile`
I'm quite confident this line won't ever work on WIndows. If  not because of ***exec*** then because of ***grep***.
So, how to test a Windows only behaviour using a test suite definitely not working on Windows ?

**Comment by muuki88** [comment]
Thanks a lot for taking the time to consider this 🥰 I fully understand if this is too cumbersome to do 😊

I'll merge and release this next week and maybe I'll find someone who has time and a dev setup that allows easier testing.

Regarding the setting. We can always start without and introduce later.

**Comment by muuki88** [comment]
`v1.7.3` is on its way

**Pull request merged**
