### PR TITLE
AshScriptPlugin - pass arguments loaded from script conf file

### LINKED ISSUE #702: javaOptions in Universal ignored by AshScriptPlugin
Tested with sbt-native-packager 1.0.5

### PR DESCRIPTION
**Pull request by pawelkaczor**
Fixes #702

### CODE REVIEW

**Comment by muuki88** [comment]
Thanks :)

**Comment by dhoepelman** [comment]
@pawelkaczor 
What's the reason`$@` and $app_mainclass switched positions? Seems like quite a breaking change (for a minor version), at least it was for our app.

Wouldn't something like

```
[ -f "$script_conf_file" ] && set -- $(loadConfigFile "$script_conf_file") "$opts"
java -classpath $app_classpath "$opts" $app_mainclass $@
```

be more appropriate?

**Comment by muuki88** [comment]
You are right. Can you provide a PR fixing this?

**Comment by dhoepelman** [comment]
Sure, #766

**Pull request merged**
