### PR TITLE
Fix scala deprecation warnings

### PR DESCRIPTION
**Pull request by Divyanshu075**

### CODE REVIEW

**Comment by Divyanshu075** [comment]
closed

**Comment by muuki88** [comment]
but why

**Comment by Divyanshu075** [comment]
@muuki88 

There is some weird issue on my local when I am building it says to use `Sync.sync(cache, FileInfo.hash)(copies)` but on the ci/cd pipeline, it says no method found.

**Comment by muuki88** [comment]
I guess it is due to the cross building. Native packager builds against sbt 0.13 and 1.x

**Comment by Divyanshu075** [comment]
Yes, Thanks for the information 👍

**Pull request closed without merging**
