### PR TITLE
Fix ash template

### LINKED ISSUE #1302: AshScriptPlugin uses bash syntax to process args
## Expected behaviour

`sbt docker:stage` should generate an `ash`/`dash` compatible script in `target/docker/stage/opt/docker/bin`

## Actual behaviour

The generated script contains syntax specific to bash (and other less posixy shells). Specifically, the generated `process_args ()` function uses the `[[` syntax for `test`, which is not available in strictly compliant shells like as `ash` and `dash`.

## Information

- What sbt-native-packager are you using: 1.6.0
- What sbt version: 1.2.8
- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian ): OS X and Ubuntu
- What package are you building: docker
- What version has your build tool: 
(this is my local version, but I've also seen it in our CI builds, which are Ubuntu-based, but run the same docker version)
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
- What is your target system: For the docker image, our base image is based off adoptopenjdk-13-bionic (though we execute the build with with the system openjdk 8 due to incompatibilities between our internal build plugin and sbt 1.3.x)

This is actually pretty easy to fix; it was brought in on #1255, and you can see it on [line 61](https://github.com/sbt/sbt-native-packager/blob/master/src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/ash-template#L61) and [lines 83 and 84](https://github.com/sbt/sbt-native-packager/blob/master/src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/ash-template#L83-L84). Fortunately, if you don't have args to parse, or are running on a base image where `/bin/sh` really is bash, the script works fine, but if you need to parse args on `ash`/`dash`, I expect you will not get the desired behavior. 

If I get the chance to later this week I'll try to open a PR for it, but thought I'd give ya'll a heads up.

### PR DESCRIPTION
**Pull request by gregsymons**
This fixes #1302, and, in a much simpler way than #1276, #1264. Unfortunately, I don't understand the tests well enough to figure out where to hang a test for the bashisms specifically, nor the `addResidual` change. If you can give me some tips, I'd be glad to write them if you want me to.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @gregsymons,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by gregsymons** [comment]
Clearly, I didn't understand the tests enough to see that there was already a test. That I have now made fail 😄. I'll be taking a closer look at this closer to the end of the week.

**Comment by muuki88** [comment]
Thanks @gregsymons for starting another take on since :hugs: 

I guess #1276 is the way forward to split `bash` and `ash` into two separate plugins to make it more explicit what is used.

Having said that, I have no idea when this will be ready to merge. So I'm happy to merge your solution to makes things work in the mean time.

**Comment by gregsymons** [comment]
BTW, is there a way to see the output from the failure in the checks? Or is my best bet to get it to fail locally and inspect it there?

**Comment by gregsymons** [comment]
I've got it working now, so once the checks pass, I'm ready to merge unless you'd like me to make any changes.

**Comment by gregsymons** [comment]
Looks like the windows tests are failing for the same reason on other PRs, so I don't think I'm going to chase it down here. I'm ready for review.

**Pull request merged**
