### PR TITLE
Issue 1382: Detect config files regardless of execute permission

### PR DESCRIPTION
**Pull request by salehdeh76**
Fixes #1383 
Fixing the order of processing linux mapping files so the conf files are always treated as conf regarless of permission

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @salehdeh76,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by muuki88** [comment]
Sorry that the build fails. There seems to be an issue regarding github actions.

**Comment by muuki88** [comment]
Adressed in #1384

**Comment by lightbend-cla-validator** [comment]
Hi @salehdeh76,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by muuki88** [comment]
Branch updated

**Comment by muuki88** [comment]
@salehdeh76 thanks for pull request :heart: Can you sign the CLA then this is good to go :smiley:

**Review by muuki88 — APPROVED** [review]

**Comment by salehdeh76** [comment]
> @salehdeh76 thanks for pull request ❤️ Can you sign the CLA then this is good to go 😃

@muuki88 Thank you. Yes I've signed it. But just don't know how to trigger the but to recheck the issue! 😃

**Pull request merged**
