### PR TITLE
Fix generated chown command (#1151)

### PR DESCRIPTION
**Pull request by mcenkar**
#1151

### CODE REVIEW

**Comment by muuki88** [comment]
Thanks for your pull request 🤗🤩

Can you give a bit more details on what issue this fixes and how you ran into it?

A regression test would be helpful for future changes 😊

**Comment by mcenkar** [comment]
Hi @muuki88 ,

I tried to put detail into related issue: https://github.com/sbt/sbt-native-packager/issues/1151

Basically we have files with $$ in name, and without single quotes around filename it gets replaced with PID, try on your box:

```
$ echo $$
3548
```
I was thinking of writing a test, but there's nothing currently there and it's an inner helper method :cry:

```
  private[debian] def makeChownReplacements(mappings: Seq[LinuxPackageMapping],
                                            streams: TaskStreams): (String, String) = {
    // how to create the chownCmd. TODO maybe configurable?
    def chownCmd(user: String, group: String)(path: String): String =
      s"chown $user:$group '$path'"
```

**Comment by muuki88** [comment]
Ah! My bad. I overlooked the #1151 reference.

> I was thinking of writing a test, but there's nothing currently there and it's an inner helper method :cry: 

Most of the stuff is tested via `sbt scripted` :smile: Take a look at [src/sbt-test/debian](https://github.com/sbt/sbt-native-packager/tree/master/src/sbt-test/debian). You can either add it to an existing test or create new one :+1:

**Comment by mcenkar** [comment]
Thanks for info, I adjusted debian tests :+1: :smile:

**Comment by mcenkar** [comment]
@muuki88 Thanks for approving, tests seemed to be stuck so I rebased. Still stuck on previous build though :cry: Any chance to get this out as official release or snapshot tomorrow?

**Comment by muuki88** [comment]
Looks like we killed Travis 😅 I'm currently testing an automated release from Travis and things got stuck a few times. Probably because the project asks for a lot of build resources.

If the new release process works, I might be able to get something out tomorrow ☺️

**Comment by muuki88** [comment]
Once more :)

**Comment by mcenkar** [comment]
@muuki88 Hi, any chance to get this out as a released package/snapshot?

**Comment by muuki88** [comment]
Release `1.3.7` this morning :)

**Pull request merged**
