### PR TITLE
Don't write RPM standard output as error

### PR DESCRIPTION
**Pull request by Falmarri**
Currently stdout for building an RPM gets output at error level. 

```
[error] + umask 022
[error] + cd /home/david/test/target/rpm/BUILD
[error] + /bin/rm -rf /home/david/test/target/rpm/buildroot
[error] + exit 0
```

### CODE REVIEW

**Comment by kardapoltsev** [comment]
Hi! Changes look good to me. Could you fix scalafmt errors please? (check travis build)

**Comment by Falmarri** [comment]
Sure. I did this in the github UI 😊

**Comment by muuki88** [comment]
@Falmarri thanks for fixing this! :heart_eyes:  I lived under the impression that `log` would already do this an `rpm` simply emits to `stderr`

**Comment by anilkumarmyla** [comment]
does this work? Just tried this on linux (`rpm-build-4.11.3-35.el7.x86_64`) & mac (`rpm 4.14.2.1`), but the [error] log is still present

**Comment by Falmarri** [comment]
Hmm. it's possible that I incorrectly identified the problem and that rpm outputting to stderr is actually the root cause. I'll inspect the rpm command more

**Comment by Falmarri** [comment]
OK you guys are right. It does write the output to stderr regardless. How about this? https://github.com/sbt/sbt-native-packager/pull/1212

**Pull request merged**
