### PR TITLE
daemonStdoutLogFile setting implemented

### PR DESCRIPTION
**Pull request by kardapoltsev**
I hope that this PR will not brake current `Rpm` behaviour.

### CODE REVIEW

**Comment by muuki88** [comment]
@kardapoltsev thanks for your PR. The purpose is to provide a stdout logfile for `systemv`, right?

Some tests failed due to a different script layout:
```
[error] 	rpm / path-override-rpm
[error] 	rpm / sysvinit-rpm
[error] 	rpm / test-executableScriptName
```

**Comment by kardapoltsev** [comment]
>> The purpose is to provide a stdout logfile for systemv, right?

Yes.
Most of rpm tests failed on my mac due to unspecified `group` config. I'll check failed tests and fix them soon.

**Comment by kardapoltsev** [comment]
@muuki88 could you take a look at this PR? I'm not sure about right order and scopes of setting overrides.

**Comment by muuki88** [comment]
Sorry @kardapoltsev , I completely forgot this one. Will take a look tomorrow.

**Comment by muuki88** [comment]
LGTM. The settings overrides and scope look correctly.

**Pull request merged**
