### PR TITLE
Additional tests and fix for #563.

### PR DESCRIPTION
**Pull request by metasim**

### CODE REVIEW

**Comment by muuki88** [comment]
Travis as problems again :/

**Comment by muuki88** [comment]
Code LGTM

**Comment by kardapoltsev** [comment]
LGTM too except `println` (: 
You could use `streams.log` instead.

**Comment by metasim** [comment]
@kardapoltsev `println` was just in the scripted test, as it swallows log output by default, and more feedback was needed there. BTW, I was having problems with scripted; calling `> clean` wasn't cleaning, and calling `> set maintainer := "" ` caused an error. Anyone know where to file bugs against `scripted`?

**Pull request merged**
