### PR TITLE
Log rpm output to error or info depending on exit code

### PR DESCRIPTION
**Pull request by Falmarri**

### CODE REVIEW

**Comment by anilkumarmyla** [comment]
@Falmarri did you get to test this change?

**Comment by Falmarri** [comment]
I didn't test it by actually running it. But I don't see how this couldn't do what is desired 😨

**Comment by anilkumarmyla** [comment]
It does work @Falmarri . Did a `sbt publishLocal` and tested resulting version in a project which logged all rpm build to info instead of error

**Comment by anilkumarmyla** [comment]
any actions on this?

**Pull request merged**
