### PR TITLE
docker: tag -f is deprecated

### LINKED ISSUE #818: docker: tag -f is deprecated
As of docker 1.10.1 `-f flag on docker tag` is deprecated and removed in 1.2.0:

```scala
val latestCmd = Seq("docker", "tag", "-f", tag, name)
```

https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala#L284

They explain the motivation for removing it as follows:
>To make tagging consistent across the various docker commands, the -f flag on the docker tag command is deprecated. It is not longer necessary to specify -f to move a tag from one image to another. Nor will docker generate an error if the -f flag is missing and the specified tag is already in use.

So, can we please remove that usage?

### PR DESCRIPTION
**Pull request by sgrankin**
fixes #818

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @sgrankin,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by typesafehub-validator** [comment]
Hi @sgrankin,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by sgrankin** [comment]
CLA signed; changed verified locally

**Comment by muuki88** [comment]
Thanks for the quick PR :)

**Pull request merged**
