### PR TITLE
update version of ant from 1.10.5 to 1.10.9

### PR DESCRIPTION
**Pull request by Divyanshu075**

### CODE REVIEW

**Comment by Divyanshu075** [comment]
@muuki88 Sent you the invitation to add as a collaborator, Please accept it so as I can add you as a reviewer.
Thank you

**Comment by muuki88** [comment]
Hi @Divyanshu075 

Thanks for keeping the dependencies up to date. Does this solve an issue that you had in your build?

> Sent you the invitation to add as a collaborator, Please accept it so as I can add you as a reviewer

Not sure what you mean by that, but pinging me is also fine :wink:

**Review by muuki88 — APPROVED** [review]

**Comment by Divyanshu075** [comment]
@muuki88 Thank you so much and really appreciate your fast response.

**ant-1.10.5** version is vulnerable to a security risk, and the only way it's injected into my project is via sbt-native-packager so I fixed them at both places.

I hope this explains the reason for updating the ant version.

Thank you :)

**Comment by muuki88** [comment]
That makes perfect sense. Thanks for the pull request 🥰

**Pull request merged**
