### PR TITLE
maintainer file names were missing

### PR DESCRIPTION
**Pull request by zoosky**
I had to look it up in the source code..

### CODE REVIEW

**Comment by muuki88** [comment]
You can remove all the `rpmXXX` settings as well. These are deprecated and will be removed. Thanks for helping to improve the docs :)

**Comment by muuki88** [comment]
@zoosky do you have time for the removal of the `rpmXXX` settings? If not, I will try to amend the changes to this pr.

**Comment by zoosky** [comment]
Voila. Hope this is what you expected.

**Comment by muuki88** [comment]
Great. Thanks 😃

**Pull request merged**
