### PR TITLE
Codacy recommended cleanup.

### PR DESCRIPTION
**Pull request by myyk**
This should not be a functional change. It is just some of recommended clean up from https://www.codacy.com/public/nepomukseiler/sbt-native-packager/dashboard

I was just snooping and figured, might as well fix a couple.

### CODE REVIEW

**Comment by muuki88** [comment]
Nice. Thanks :)

**Comment by muuki88** [comment]
There is a change in logic, which [broke the tests](https://ci.appveyor.com/project/muuki88/sbt-native-packager/build/28#L494). However I'm not sure why the windows tests only run on my PRS.

Can you provide a second pull request?

**Comment by muuki88** [comment]
The error

```scala
if (f == null) Seq() else Seq(f) ++ allParentDirs(f.getParentFile)
// with braces
if (f == null) { Seq() } else { Seq(f) ++ allParentDirs(f.getParentFile) }

// so this would be
Option(f).map(f => f :+ allParentDirs(f.getParentFile) ) getOrElse Seq()
```

**Comment by myyk** [comment]
Oh, sorry about that. Yeah, that's clearer with braces. What do you think about this? It preserves the ordering as well.

Option(f).toSeq.flatMap(f => f +: allParentDirs(f.getParentFile))

**Comment by myyk** [comment]
I wasn't sure how to test my own change. I think I now have [appveyor](https://ci.appveyor.com/project/myyk/sbt-native-packager/build/3) setup correctly so that I can test the fix myself before making the pull request this time.

**Comment by muuki88** [comment]
Oh xD This is a misconfiguration on our side. Have to check when I'm back in Germany why appveyor is no running on pull request that don't come from this repo. However thanks for testing this :+1: 

LGTM

**Pull request merged**
