### PR TITLE
Add addApp function to align with bash version

### PR DESCRIPTION
**Pull request by olsio**
Closes https://github.com/sbt/sbt-native-packager/issues/862

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @olsio,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by olsio** [comment]
Signed the CLA

**Comment by muuki88** [comment]
Thanks a lot for adding this feature ♥️

It would be awesome to add one sbt-test to validate that this feature works with future changes.

https://github.com/sbt/sbt-native-packager/tree/master/src/sbt-test/ash/command-line-settings

You can checkout the [dev guidelines](https://github.com/sbt/sbt-native-packager/wiki/Developer-Guide) for pointers on how to run the tests.

**Comment by olsio** [comment]
Sure will have a look.

**Comment by olsio** [comment]
I added the test. It wouldn't build on MacOS so I had to find a Ubuntu machine first.

In general it might be a good idea to remove this plug-in all together and just have a single JavaAppPackaging version of the script without relying on bash. But I don't know what the implications of that would be.

**Comment by muuki88** [comment]
Awesome :+1: Thanks for the additional test.

> In general it might be a good idea to remove this plug-in all together and just have a single JavaAppPackaging version of the script without relying on bash

From an engineering perspective I would agree to find the smallest common denominator and remove the additional stuff. My bare minimum bash knowledge is afraid of doing such a thing.

> But I don't know what the implications of that would be.

Me neither :joy: I have merged like 1-5 pull request each year adding a bit more "bash magic" to make certain use cases work. Bash is really string escaping hell. So at this point I'm okay with maintaining an ash and bash implementation as I have to find someone willing to backport all the weird bash hacks I don't quite understand :disappointed: 

So in general yes :heart: If you want to do it, I'll give you as much support as I can :hugs:

**Pull request merged**
