### PR TITLE
Fix dockerVersion command creation

### LINKED ISSUE #1051: After upgrading to version 1.3.0, sbt started throwing "docker: 'version --format '{{.Server.Version}}'' not a docker command" warnings on console
## Expected behaviour
Upgrading to packager version 1.3.0 should not result into any warnings on console
E.g. Just run `sbt`

## Actual behaviour
After upgrading to sbt-native-packager 1.3.0, can see following warnings on sbt console:
docker: 'version --format '{{.Server.Version}}'' is not a docker command.

I have docker v17.09.0-ce-mac35 (19611) installed on my machine and it does give me correct version when above command is run from separate terminal:
`~/T/csw-prod:master$ docker version --format '{{.Server.Version}}'`
`17.09.0-ce`

## Information

- What sbt-native-packager are you using?
1.3.0

- What sbt version
1.0.2

- What is your build system (e.g. Ubuntu, MacOS, Windows, Debian )
macOs (iterm2 3.1.3)

### PR DESCRIPTION
**Pull request by mrfyda**
Fixes #1051

### CODE REVIEW

**Comment by muuki88** [comment]
@mrfyda are you interested in becoming more involved with sbt-native-packager?
I'm more than happy to have more people on board maintaining this project :)

**Comment by NeQuissimus** [comment]
@muuki88 Can you cut a release for this?

**Comment by NeQuissimus** [comment]
Thank you :)

**Comment by muuki88** [comment]
`1.3.1` is out

**Comment by mrfyda** [comment]
@muuki88 Thanks for the release. Let me know how I can help.

**Comment by muuki88** [comment]
Sorry, lost track of your answer 😄 
Any help is welcome. You are already contributing well done code contributions.
I'm giving you commit rights, so you could review and merge other peoples PRs
if you feel comfortable doing so and have the time and motivation to.

Even if this sounds obvious: Everything, yet so seemingly small help, is awesome,
but if you aren't forced to do anything. The native-packager community is small,
with friendly, helpful and open-minded people. It should always be enjoyable
contributing here 😃 

If you like, we can hangout/skype 😄

**Pull request merged**
