### PR TITLE
Removed grep invocations from rpm postun script

### PR DESCRIPTION
**Pull request by jkramarz**
Let's do it in simpler & more robust way...

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @jkramarz,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://typesafe.com/contribute/cla](http://typesafe.com/contribute/cla)

**Comment by kardapoltsev** [comment]
LGTM. Lets wait for travis (:

**Comment by muuki88** [comment]
Nice. I think we should change this in [control-functions](https://github.com/sbt/sbt-native-packager/blob/master/src/main/resources/com/typesafe/sbt/packager/linux/control-functions) as well, or better remove this from `rpm` and just use the `add/delete Group/User` functions.

**Comment by jkramarz** [comment]
@muuki88: Ok, I'll take a bit deeper look at this part of code, so let's close this PR without merging for now.

**Comment by muuki88** [comment]
I think the refactoring didn't finish this last piece.

```bash
if getent passwd "${{daemon_user}}" > /dev/null;
```

is just redudant, so you can this check in the `control-functions` and
in the `rpm` scriptlets.

**Pull request closed without merging**
